from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
import uipy

class MainWindowUi(object):
    def setupUi(self, MainWindow:QMainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.resize(413, 403)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(413, 403))
        MainWindow.setMaximumSize(QtCore.QSize(413, 403))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(uipy.MAIN_ICON), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_save_passwords = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_save_passwords.setMinimumSize(QtCore.QSize(28, 0))
        self.pushButton_save_passwords.setMaximumSize(QtCore.QSize(28, 16777215))
        self.pushButton_save_passwords.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(uipy.SAVE_ICON), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_save_passwords.setIcon(icon1)
        self.pushButton_save_passwords.setObjectName("pushButton_save_passwords")
        self.horizontalLayout_3.addWidget(self.pushButton_save_passwords)
        self.pushButton_show_saved_passwords = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_show_saved_passwords.setObjectName("pushButton_show_saved_passwords")
        self.horizontalLayout_3.addWidget(self.pushButton_show_saved_passwords)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_5)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.spinBox_password_length = QtWidgets.QSpinBox(parent=self.frame_5)
        self.spinBox_password_length.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_password_length.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_password_length.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBox_password_length.setReadOnly(False)
        self.spinBox_password_length.setProperty("showGroupSeparator", False)
        self.spinBox_password_length.setMinimum(6)
        self.spinBox_password_length.setMaximum(32)
        self.spinBox_password_length.setProperty("value", 8)
        self.spinBox_password_length.setObjectName("spinBox_password_length")
        self.horizontalLayout_2.addWidget(self.spinBox_password_length)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.checkBox_symbols = QtWidgets.QCheckBox(parent=self.frame_4)
        self.checkBox_symbols.setObjectName("checkBox_symbols")
        self.verticalLayout_3.addWidget(self.checkBox_symbols)
        self.checkBox_numbers = QtWidgets.QCheckBox(parent=self.frame_4)
        self.checkBox_numbers.setObjectName("checkBox_numbers")
        self.verticalLayout_3.addWidget(self.checkBox_numbers)
        self.checkBox_lowercase_char = QtWidgets.QCheckBox(parent=self.frame_4)
        self.checkBox_lowercase_char.setObjectName("checkBox_lowercase_char")
        self.verticalLayout_3.addWidget(self.checkBox_lowercase_char)
        self.checkBox_uppercase_char = QtWidgets.QCheckBox(parent=self.frame_4)
        self.checkBox_uppercase_char.setObjectName("checkBox_uppercase_char")
        self.verticalLayout_3.addWidget(self.checkBox_uppercase_char)
        self.checkBox_repeated_char = QtWidgets.QCheckBox(parent=self.frame_4)
        self.checkBox_repeated_char.setObjectName("checkBox_repeated_char")
        self.verticalLayout_3.addWidget(self.checkBox_repeated_char)
        self.checkBox_ambiguous_char = QtWidgets.QCheckBox(parent=self.frame_4)
        self.checkBox_ambiguous_char.setObjectName("checkBox_ambiguous_char")
        self.verticalLayout_3.addWidget(self.checkBox_ambiguous_char)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_generated_password = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_generated_password.setObjectName("lineEdit_generated_password")
        self.lineEdit_generated_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_generated_password.setReadOnly(True)
        self.horizontalLayout.addWidget(self.lineEdit_generated_password)
        self.pushButton_generate_password = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_generate_password.setObjectName("pushButton_generate_password")
        self.horizontalLayout.addWidget(self.pushButton_generate_password)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.pushButton_save_generated_password = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_save_generated_password.setObjectName("pushButton_save_generated_password")
        self.verticalLayout_2.addWidget(self.pushButton_save_generated_password)
        self.pushButton_save_my_password = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_save_my_password.setObjectName("pushButton_save_my_password")
        self.verticalLayout_2.addWidget(self.pushButton_save_my_password)
        self.verticalLayout_4.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SwiftPass"))
        self.pushButton_show_saved_passwords.setText(_translate("MainWindow", "Show saved passwords"))
        self.label.setText(_translate("MainWindow", "Password Length :"))
        self.checkBox_symbols.setText(_translate("MainWindow", "Include Symbols (eg. @#$%)"))
        self.checkBox_numbers.setText(_translate("MainWindow", "Include Numbers (eg. 123)"))
        self.checkBox_lowercase_char.setText(_translate("MainWindow", "Include Lowercase Characters (eg. abc)"))
        self.checkBox_uppercase_char.setText(_translate("MainWindow", "Include Uppercase Characters (eg. ABC)"))
        self.checkBox_repeated_char.setText(_translate("MainWindow", "Exclude Repeated Characters (eg. aAbBcC)"))
        self.checkBox_ambiguous_char.setText(_translate("MainWindow", "Include Ambiguous Characters(eg. {}[],.)"))
        self.pushButton_generate_password.setText(_translate("MainWindow", "Generate"))
        self.pushButton_save_generated_password.setText(_translate("MainWindow", "Save Password"))
        self.pushButton_save_my_password.setText(_translate("MainWindow", "My Password"))
